// Generated by view binder compiler. Do not edit!
package net.hearnsoft.setupwizard.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import net.hearnsoft.setupwizard.R;

public final class FragmentMiscViewBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final LinearLayout backupSettings;

  @NonNull
  public final LinearLayout googleSettings;

  @NonNull
  public final LinearLayout lockSettings;

  private FragmentMiscViewBinding(@NonNull FrameLayout rootView,
      @NonNull LinearLayout backupSettings, @NonNull LinearLayout googleSettings,
      @NonNull LinearLayout lockSettings) {
    this.rootView = rootView;
    this.backupSettings = backupSettings;
    this.googleSettings = googleSettings;
    this.lockSettings = lockSettings;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentMiscViewBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentMiscViewBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_misc_view, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentMiscViewBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.backup_settings;
      LinearLayout backupSettings = ViewBindings.findChildViewById(rootView, id);
      if (backupSettings == null) {
        break missingId;
      }

      id = R.id.google_settings;
      LinearLayout googleSettings = ViewBindings.findChildViewById(rootView, id);
      if (googleSettings == null) {
        break missingId;
      }

      id = R.id.lock_settings;
      LinearLayout lockSettings = ViewBindings.findChildViewById(rootView, id);
      if (lockSettings == null) {
        break missingId;
      }

      return new FragmentMiscViewBinding((FrameLayout) rootView, backupSettings, googleSettings,
          lockSettings);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
